// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoIOS13npDTU6y76-t6-dE6QfdQbiqro',
    appId: '1:511400534038:web:40f857d324abc22d195537',
    messagingSenderId: '511400534038',
    projectId: 'prayertime-20de9',
    authDomain: 'prayertime-20de9.firebaseapp.com',
    storageBucket: 'prayertime-20de9.appspot.com',
    measurementId: 'G-L57K3ZQHGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPIm6IhcrpmQxiz6qD3FctAF1rPmE751E',
    appId: '1:511400534038:android:e037ac3dfb849024195537',
    messagingSenderId: '511400534038',
    projectId: 'prayertime-20de9',
    storageBucket: 'prayertime-20de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7AapAM63jfi88eqrqnDFeTzvjOG15nM',
    appId: '1:511400534038:ios:8939c805a0a215be195537',
    messagingSenderId: '511400534038',
    projectId: 'prayertime-20de9',
    storageBucket: 'prayertime-20de9.appspot.com',
    iosBundleId: 'com.example.prayertimeDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7AapAM63jfi88eqrqnDFeTzvjOG15nM',
    appId: '1:511400534038:ios:c5988151ffa736ad195537',
    messagingSenderId: '511400534038',
    projectId: 'prayertime-20de9',
    storageBucket: 'prayertime-20de9.appspot.com',
    iosBundleId: 'com.example.prayertimeDashboard.RunnerTests',
  );
}
